module.exports = {
    transform: {
        "^.+\\.js$": "babel-jest",
    },
    type: "module",
    modulePathIgnorePatterns: ["<rootDir>/dist/"],
    maxConcurrency: 7,
    testMatch: [
        // "**/auth.test.js",
        // "**/account.test.js",
        // "**/user.test.js",
        // "**/address.test.js",
        // "**/chat.test.js",
        // "**/message.test.js",
        // "**/notification.test.js",
        // "**/store.test.js",
        // "**/business.test.js",
        // "**/product.test.js",
        // "**/product-variation.test.js",
        // "**/stock.test.js",
        // "**/order.test.js",
        // "**/transaction.test.js",
        // "**/category.test.js",
        // "**/review.test.js",
        // "**/rating.test.js",
        // "**/reply.test.js",
        // "**/delivery.test.js",
        // "**/cart.test.js",
        // "**/report.test.js",
        // "**/suspension.test.js",
    ],
};
